# --- !Ups

create table "players" (
  "id" bigint generated by default as identity(start with 1) not null primary key,
  "firstName" varchar not null,
  "lastName" varchar not null
);

create table "matches" (
  "id" bigint generated by default as identity(start with 1) not null primary key,
  "startDate" time not null,
  "endDate" time not null
);


# --- !Downs

drop table "players" if exists;
drop table "matches" if exists;
